// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.DB.Models
{
    public partial class Category
    {
        public Category()
        {
            ProductsInCategories = new HashSet<ProductsInCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ProductsInCategory> ProductsInCategories { get; set; }
    }
}