// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.DB.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductImages = new HashSet<ProductImage>();
            ProductsInCategories = new HashSet<ProductsInCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Quantuty { get; set; }
        public decimal Price { get; set; }
        public int UnitId { get; set; }
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateChanged { get; set; }
        public DateTime? DateDeleted { get; set; }

        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductsInCategory> ProductsInCategories { get; set; }
    }
}