// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.DB.Models
{
    public partial class Role
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}